### ISSUE TITLE
Random error when enabling MCSF

### ISSUE THREAD

**Issue by t0mtee** [Jochyoua/MCSF#3]
Hi,
This plugin is AMAZING and I wanna say thanks so much for it, however, recently I've been experiencing a problem with it:
```
[10:19:50 ERROR]: Error occurred while enabling MCSF v4.1 (Is it up to date?)
java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 1                                                          
        at com.github.Jochyoua.MCSF.shared.Utils.clean(Utils.java:296) ~[?:?]                                                         
        at com.github.Jochyoua.MCSF.MCSF.onEnable(MCSF.java:162) ~[?:?]                                                               
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.1.jar:git-Paper-93]                       
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.1.jar:git-Paper-93]         
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.1.jar:git-Paper-93]        
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.1.jar:git-Paper-93]          
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:414) ~[patched_1.16.1.jar:git-Paper-93]         
        at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:471) ~[patched_1.16.1.jar:git-Paper-93]       
        at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.1.jar:git-Paper-93]            
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:940) ~[patched_1.16.1.jar:git-Paper-93]               
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-93]      
        at java.lang.Thread.run(Thread.java:834) [?:?]
```
It started randomly and I don't know what to do about it.
Thanks!

**Comment by Jochyoua** [comment]
I'll have a look tomorrow, my PC is arriving then :)

**Comment by t0mtee** [comment]
> I'll have a look tomorrow, my PC is arriving then :)

Nice, thanks.

**Comment by Jochyoua** [comment]
Alright, so l _hopefully_ fixed the issue, I'll post an update soon :) It turns out that it was me trying to find the matched word through regex

**Comment by t0mtee** [comment]
> Alright, so l _hopefully_ fixed the issue, I'll post an update soon :) It turns out that it was me trying to find the matched word through regex

Great, thanks!
