### ISSUE TITLE
major issue

### ISSUE THREAD

**Issue by gyu6378** [Jochyoua/MCSF#6]
[20:11:42] [Server thread/ERROR]: [MCSF] Failure: Failed to load Chat Filtering (FULL CHAT)!
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source) ~[?:1.8.0_211]
	at java.util.ArrayList$Itr.next(Unknown Source) ~[?:1.8.0_211]
	at org.yaml.snakeyaml.serializer.Serializer.anchorNode(Serializer.java:140) ~[patched_1.13.2.jar:git-Paper-655]
	at org.yaml.snakeyaml.serializer.Serializer.anchorNode(Serializer.java:144) ~[patched_1.13.2.jar:git-Paper-655]
	at org.yaml.snakeyaml.serializer.Serializer.serialize(Serializer.java:107) ~[patched_1.13.2.jar:git-Paper-655]
	at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:307) ~[patched_1.13.2.jar:git-Paper-655]
	at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:270) ~[patched_1.13.2.jar:git-Paper-655]
	at org.yaml.snakeyaml.Yaml.dump(Yaml.java:245) ~[patched_1.13.2.jar:git-Paper-655]
	at org.bukkit.configuration.file.YamlConfiguration.saveToString(YamlConfiguration.java:40) ~[patched_1.13.2.jar:git-Paper-655]
	at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:68) ~[patched_1.13.2.jar:git-Paper-655]
	at org.bukkit.plugin.java.JavaPlugin.saveConfig(JavaPlugin.java:172) ~[patched_1.13.2.jar:git-Paper-655]
	at io.github.Jochyoua.MyChristianSwearFilter.shared.Utils.clean(Utils.java:612) ~[?:?]
	at io.github.Jochyoua.MyChristianSwearFilter.events.ProtocolLib$1.onPacketSending(ProtocolLib.java:39) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:336) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:378) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:64) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:343) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:313) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
	at net.minecraft.server.v1_13_R2.NetworkManager.b(NetworkManager.java:209) ~[patched_1.13.2.jar:git-Paper-655]
	at net.minecraft.server.v1_13_R2.NetworkManager.sendPacket(NetworkManager.java:172) ~[patched_1.13.2.jar:git-Paper-655]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1506) ~[patched_1.13.2.jar:git-Paper-655]
	at net.minecraft.server.v1_13_R2.PlayerConnection.sendPacket(PlayerConnection.java:1479) ~[patched_1.13.2.jar:git-Paper-655]
	at sun.reflect.GeneratedMethodAccessor58.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_211]
	at com.Zrips.CMI.Modules.RawMessages.RawMessageManager.send(RawMessageManager.java:122) ~[?:?]
	at com.Zrips.CMI.Modules.RawMessages.RawMessage.show(RawMessage.java:542) ~[?:?]
	at com.Zrips.CMI.Modules.RawMessages.RawMessage.show(RawMessage.java:524) ~[?:?]
	at com.Zrips.CMI.Modules.NickName.NickNameListener$1.run(NickNameListener.java:182) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.13.2.jar:git-Paper-655]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[patched_1.13.2.jar:git-Paper-655]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1010) ~[patched_1.13.2.jar:git-Paper-655]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-655]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-655]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-655]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
[20:11:42] [Server thread/INFO]: [MCSF] Failure: If you feel as if this is a bug, post an issue here: https://git.io/Jf5L8
only filter players has been temporarily enabled.

[20:11:42] [Async Chat Thread - #126/ERROR]: Could not pass event AsyncPlayerChatEvent to MCSF v5.0
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source) ~[?:1.8.0_211]
	at java.util.ArrayList$Itr.next(Unknown Source) ~[?:1.8.0_211]
	at org.yaml.snakeyaml.serializer.Serializer.anchorNode(Serializer.java:140) ~[patched_1.13.2.jar:git-Paper-655]
	at org.yaml.snakeyaml.serializer.Serializer.anchorNode(Serializer.java:144) ~[patched_1.13.2.jar:git-Paper-655]
	at org.yaml.snakeyaml.serializer.Serializer.serialize(Serializer.java:107) ~[patched_1.13.2.jar:git-Paper-655]
	at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:307) ~[patched_1.13.2.jar:git-Paper-655]
	at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:270) ~[patched_1.13.2.jar:git-Paper-655]
	at org.yaml.snakeyaml.Yaml.dump(Yaml.java:245) ~[patched_1.13.2.jar:git-Paper-655]
	at org.bukkit.configuration.file.YamlConfiguration.saveToString(YamlConfiguration.java:40) ~[patched_1.13.2.jar:git-Paper-655]
	at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:68) ~[patched_1.13.2.jar:git-Paper-655]
	at org.bukkit.plugin.java.JavaPlugin.saveConfig(JavaPlugin.java:172) ~[patched_1.13.2.jar:git-Paper-655]
	at io.github.Jochyoua.MyChristianSwearFilter.shared.Utils.clean(Utils.java:612) ~[?:?]
	at io.github.Jochyoua.MyChristianSwearFilter.events.PlayerEvents.PlayerChatEvent(PlayerEvents.java:119) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor321.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.13.2.jar:git-Paper-655]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.13.2.jar:git-Paper-655]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-655]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-655]
	at net.minecraft.server.v1_13_R2.PlayerConnection.chat(PlayerConnection.java:1696) ~[patched_1.13.2.jar:git-Paper-655]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1611) ~[patched_1.13.2.jar:git-Paper-655]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat$1.run(PacketPlayInChat.java:39) ~[patched_1.13.2.jar:git-Paper-655]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_211]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_211]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]

**Comment by Jochyoua** [comment]
Hello. :D I am not sure what seems to be causing your issue here, but could you do me a favor and try out the latest developmental version of this plugin on our Discord server? There have been many changes since the latest release that I have not been able to push due to me being worried that it will cause significant issues. However, to my current testings, no problems have occurred. Let me know how this goes!
https://discord.gg/8q2KPPnm6U
