### ISSUE TITLE
Error in console [1.17.1]

### ISSUE THREAD

**Issue by MarcusVosper** [Jochyoua/MCSF#8]
[11:00:40 WARN]: [MCSF Debug] Failed to load Chat Filtering (FULL CHAT)!
[11:00:40 WARN]: java.lang.NullPointerException: Cannot invoke "java.util.regex.Pattern.matcher(java.lang.CharSequence)" because "pattern" is null
[11:00:40 WARN]:        at io.github.jochyoua.mychristianswearfilter.shared.Manager.filter(Manager.java:529)
[11:00:40 WARN]:        at io.github.jochyoua.mychristianswearfilter.shared.Manager.clean(Manager.java:516)
[11:00:40 WARN]:        at io.github.jochyoua.mychristianswearfilter.shared.hooks.ProtocolLib$1.onPacketSending(ProtocolLib.java:50)
[11:00:40 WARN]:        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[11:00:40 WARN]:        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[11:00:40 WARN]:        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535)
[11:00:40 WARN]:        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516)
[11:00:40 WARN]:        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:346)
[11:00:40 WARN]:        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:308)
[11:00:40 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:433)
[11:00:40 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:70)
[11:00:40 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:373)
[11:00:40 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:343)
[11:00:40 WARN]:        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127)
[11:00:40 WARN]:        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95)
[11:00:40 WARN]:        at net.minecraft.network.NetworkManager.b(NetworkManager.java:294)
[11:00:40 WARN]:        at net.minecraft.network.NetworkManager.sendPacket(NetworkManager.java:258)
[11:00:40 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1905)
[11:00:40 WARN]:        at net.minecraft.server.network.PlayerConnection.sendPacket(PlayerConnection.java:1891)
[11:00:40 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.entity.CraftPlayer.sendRawMessage(CraftPlayer.java:229)
[11:00:40 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.entity.CraftPlayer.sendMessage(CraftPlayer.java:245)
[11:00:40 WARN]:        at org.bukkit.command.defaults.PluginsCommand.execute(PluginsCommand.java:28)
[11:00:40 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[11:00:40 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821)
[11:00:40 WARN]:        at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2170)
[11:00:40 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1981)
[11:00:40 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1962)
[11:00:40 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[11:00:40 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[11:00:40 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:36)
[11:00:40 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[11:00:40 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[11:00:40 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[11:00:40 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1348)
[11:00:40 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:190)
[11:00:40 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[11:00:40 WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1327)
[11:00:40 WARN]:        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1320)
[11:00:40 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[11:00:40 WARN]:        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1281)
[11:00:40 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1192)
[11:00:40 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[11:00:40 WARN]:        at java.base/java.lang.Thread.run(Unknown Source)
[11:00:40 WARN]: [MCSF] Failure: If you feel as if this is a bug, post an issue here: https://git.io/Jf5L8

**Comment by ghost** [comment]
Also having this issue! Please update the plugin to add 1.17+ support!

**Comment by OfficialTheosis** [comment]
I had this issue on 1.16.5.
